In [ ]:
#Array introduction
import numpy as np
#Create and display zero, one, and n-dimensional arrays
zero_dim_array=np.array(5)
one_dim_array=np.array([1,2,3])
n_dim_array=np.array([[1,2],[3,4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array: \n{arr} \nDimension: {arr.ndim}\nData Type: {arr.dtype}\n")

Array: 
5 
Dimension: 0
Data Type: int64

Array: 
[1 2 3] 
Dimension: 1
Data Type: int64

Array: 
[[1 2]
 [3 4]] 
Dimension: 2
Data Type: int64



In [2]:
# Problem_1
# Complete the following Tasks:
# 1. Initialize an empty array with size 2X2.
arr=[[0,0],[0,0]]
for i in arr:
  print(i)



[0, 0]
[0, 0]


In [3]:
# 2. Initialize an all one array with size 4X2.
arr=[[0,0], [0,0], [0,0], [0,0]]
for i in arr:
  print (i)

[0, 0]
[0, 0]
[0, 0]
[0, 0]


In [5]:
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
arr=np.full((4,4),1,dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np
a=[[1,2,3], [4,5,6]]
arr=np.zeros_like(a)
print(arr)


[[0 0 0]
 [0 0 0]]


In [7]:
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np
a=[[1,2,3], [4,5,6]]
arr=np.ones_like(a)
print(arr)

[[1 1 1]
 [1 1 1]]


In [8]:
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np
new_list=[1,2,3,4]
arr=np.array(new_list)
print(arr)

[1 2 3 4]


In [12]:
#Problem_2
# Complete the following tasks:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
arr_arrange=np.arange(10,50) #start,stop,step
print(arr_arrange)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}
import numpy as np
arr=np.arange(9)
arr_reshape=arr.reshape(3,3)
print(arr_reshape)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# 4. Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
import numpy as np
arr_random=np.random.random(30)
arr_mean=arr_random.mean()
print(arr_random)
print(arr_mean)

[0.53479382 0.60730648 0.26555488 0.1984958  0.52170495 0.83286599
 0.66793148 0.40143684 0.16821108 0.11111355 0.06611919 0.58196759
 0.91269688 0.94126122 0.48805533 0.847818   0.14231876 0.60900581
 0.87214971 0.93262725 0.37974384 0.56002374 0.94901982 0.68940321
 0.41224692 0.55916923 0.31788389 0.16152836 0.68984606 0.29953049]
0.5240610061223532


In [24]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np
arr_random=np.random.randint(1, 101, size=(10,10))
arr_maxi=arr_random.max()
arr_mini=arr_random.min()
print(arr_maxi)
print(arr_mini)

98
2


In [25]:
# 6. Create a zero array of size 10 and replace 5th element with 1.
import numpy as np
arr_zero=np.zeros(10)
arr_zero[4]=1
print(arr_zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
# 7. Reverse an array arr = [1,2,0,0,4,0].
arr=[1,2,0,0,4,0]
arr_reverse=arr[::-1]
print(arr_reverse)

[0, 4, 0, 0, 2, 1]


In [34]:
# 8. Create a 2d array with 1 on border and 0 inside.
import numpy as np
size=5
arr=np.zeros((size,size))
arr[0,:]=1 #Top border
arr[-1,:]=1 # Bottom border
arr[:, 0]=1 #left border
arr[:,-1]=1 #right border
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np
size = 8
arr = np.zeros((size, size))

arr[::2, ::2] = 1  # Set 1 for even rows and even columns
arr[1::2, 1::2] = 1  # Set 1 for odd rows and odd columns

print("Checkerboard Pattern Array:\n", arr)


Checkerboard Pattern Array:
 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [43]:
#Problem 3
# For the following arrays:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
add=x+y
print(add)
print("------")
# 2. Subtract the two array.
sub=v-w
print(sub)
print("-------")
# 3. Multiply the array with any integers of your choice.
multi=x*2
print(multi)
print("--------")
# 4. Find the square of each element of the array.
square=np.square(x)
print(square)
print("--------")
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_product1=np.dot(v,w)
dot_product2=np.dot(x,v)
dot_product3=np.dot(x,y)
print(dot_product1)
print(dot_product2)
print(dot_product3)
print("---------")
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenate x and y along rows:\n", concat_xy_row)
print("Concatenate v and w along columns:\n", concat_vw_col)
print("--------")

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenated x and v:\n", concat_xv)
except Exception as e:
    print("Error:", e)


[[ 6  8]
 [10 13]]
------
[-2 -2]
-------
[[ 2  4]
 [ 6 10]]
--------
[[ 1  4]
 [ 9 25]]
--------
219
[29 77]
[[19 22]
 [50 58]]
---------
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]
--------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [44]:
#Problem 4
# • For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
# 2. Prove AB ≠ BA.
# 3. Prove (AB)
# T = BTAT
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
identity_matrix = np.dot(A, A_inv)

print("A * A^-1:\n", identity_matrix)

# Multiply A and B
AB = np.dot(A, B)

# Multiply B and A
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

# Check if AB is equal to BA
are_equal = np.array_equal(AB, BA)
print("Is AB equal to BA?", are_equal)

# Compute (AB)^T
AB_transpose = np.transpose(np.dot(A, B))

# Compute B^T * A^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("Transpose of AB:\n", AB_transpose)
print("B^T * A^T:\n", BT_AT)

# Check if they are equal
are_equal_transpose = np.array_equal(AB_transpose, BT_AT)
print("Is (AB)^T equal to B^T A^T?", are_equal_transpose)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False
Transpose of AB:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T? True


In [45]:
# Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
import numpy as np

# Define the matrix A (coefficients) and B (constants)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse method
X = np.dot(A_inv, B)

print("Solution for [x, y, z]:", X)


Solution for [x, y, z]: [ 2.  1. -2.]


In [46]:
#Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
#of Numpy}
import numpy as np

# Define the matrix A (coefficients) and B (constants)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the inverse of A using np.linalg.inv
A_inv = np.linalg.inv(A)

# Solve for X using the inverse method
X = np.dot(A_inv, B)

print("Solution for [x, y, z]:", X)


Solution for [x, y, z]: [ 2.  1. -2.]
